package tutorials

import (
	"fyne.io/fyne/v2"
)

// Tutorial defines the data structure for a tutorial
type Tutorial struct {
	Title, Intro string
	View         func(w fyne.Window) fyne.CanvasObject
}

var (
	// Tutorials defines the metadata for each tutorial
	Tutorials = map[string]Tutorial{
		"welcome": {"首页", "HomePage", welcomeScreen},
		"canvas": {"画图",
			"See the canvas capabilities.",
			canvasScreen,
		},
		"animations": {"渐进变化",
			"See how to animate components.",
			makeAnimationScreen,
		},
		"icons": {"主题和图标",
			"Browse the embedded icons.",
			iconScreen,
		},
		"containers": {"容器",
			"Containers group other widgets and canvas objects, organising according to their layout.\n" +
				"Standard containers are illustrated in this section, but developers can also provide custom " +
				"layouts using the fyne.NewContainerWithLayout() constructor.",
			containerScreen,
		},
		"apptabs": {"tab栏",
			"A container to help divide up an application into functional areas.",
			makeAppTabsTab,
		},
		"border": {"边框",
			"A container that positions items around a central content.",
			makeBorderLayout,
		},
		"box": {"盒模型",
			"A container arranges items in horizontal or vertical list.",
			makeBoxLayout,
		},
		"center": {"居中布局",
			"A container to that centers child elements.",
			makeCenterLayout,
		},
		"doctabs": {"文档tab",
			"A container to display a single document from a set of many.",
			makeDocTabsTab,
		},
		"grid": {"网格模型",
			"A container that arranges all items in a grid.",
			makeGridLayout,
		},
		"split": {"拆分",
			"A split container divides the container in two pieces that the user can resize.",
			makeSplitTab,
		},
		"scroll": {"滚动条",
			"A container that provides scrolling for it's content.",
			makeScrollTab,
		},
		"widgets": {"小组件",
			"In this section you can see the features available in the toolkit widget set.\n" +
				"Expand the tree on the left to browse the individual tutorial elements.",
			widgetScreen,
		},
		"accordion": {"折叠栏",
			"Expand or collapse content panels.",
			makeAccordionTab,
		},
		"button": {"按钮",
			"Simple widget for user tap handling.",
			makeButtonTab,
		},
		"card": {"卡片",
			"Group content and widgets.",
			makeCardTab,
		},
		"entry": {"抽屉",
			"Different ways to use the entry widget.",
			makeEntryTab,
		},
		"form": {"表单",
			"Gathering input widgets for data submission.",
			makeFormTab,
		},
		"input": {"输入",
			"A collection of widgets for user input.",
			makeInputTab,
		},
		"text": {"文本",
			"Text handling widgets.",
			makeTextTab,
		},
		"toolbar": {"工具栏",
			"A row of shortcut icons for common tasks.",
			makeToolbarTab,
		},
		"progress": {"进度条",
			"Show duration or the need to wait for a task.",
			makeProgressTab,
		},
		"collections": {"集合",
			"Collection widgets provide an efficient way to present lots of content.\n" +
				"The List, Table, and Tree provide a cache and re-use mechanism that make it possible to scroll through thousands of elements.\n" +
				"Use this for large data sets or for collections that can expand as users scroll.",
			collectionScreen,
		},
		"list": {"列表",
			"A vertical arrangement of cached elements with the same styling.",
			makeListTab,
		},
		"table": {"表格",
			"A two dimensional cached collection of cells.",
			makeTableTab,
		},
		"tree": {"树形结构",
			"A tree based arrangement of cached elements with the same styling.",
			makeTreeTab,
		},
		"dialogs": {"对话框",
			"Work with dialogs.",
			dialogScreen,
		},
		"windows": {"窗口",
			"Window function demo.",
			windowScreen,
		},
		"binding": {"数据绑定",
			"Connecting widgets to a data source.",
			bindingScreen},
		"advanced": {"高级功能",
			"Debug and advanced information.",
			advancedScreen,
		},
	}

	// TutorialIndex  defines how our tutorials should be laid out in the index tree
	TutorialIndex = map[string][]string{
		"":            {"welcome", "canvas", "animations", "icons", "widgets", "collections", "containers", "dialogs", "windows", "binding", "advanced"},
		"collections": {"list", "table", "tree"},
		"containers":  {"apptabs", "border", "box", "center", "doctabs", "grid", "scroll", "split"},
		"widgets":     {"accordion", "button", "card", "entry", "form", "input", "progress", "text", "toolbar"},
	}
)
